### ISSUE TITLE
Condition update

### ISSUE THREAD

**Issue by jakemiller13** [eric-hunt/unclePy#4]
Use Daria's metadata

**Comment by eric-hunt** [comment]
@jakemiller13 – Is this writing a value for `conditions.type` from the temporary recode metadata we created or is this from the existing metadata Excel document? I am still performing the temporary recode as it seems there is no type associated with some `conditions.name` present in the experiments. We should consider this when new plate templates are created so the user explicitly defines the category each additive falls into.

**Comment by eric-hunt** [comment]
Small request to change the string for pH condition.type from "Ph" to "pH"..

**Comment by jakemiller13** [comment]
@eric-hunt I realize how ridiculous this sounds, but it's actually going to be very complicated to change Ph to pH. Due to Ruby's (occasionally uncomfortable) "convention over configuration", all class names must start capitalized. And due to how the database was originally designed years ago, "condition types" are actually subclasses of a condition. So I would either need to modify the Ruby source code (bad idea) or modify the database design which would have serious repercussions across all of ebase... I'm not sure if there might be some way to write a Postgres function to modify the string during a `select`, but would it be easy to change it when you display it in the app?

**Comment by jakemiller13** [comment]
Closing because this is being handled via Ruby seeds
